### ISSUE TITLE
Not able to connect to dashboard at http://42.2.153.218:9090//

### ISSUE THREAD

**Issue by f-thomson** [Lisandro79/BeatTheBookie#19]
It does not let me connect to dashboard. The connection times out.

**Comment by Lisandro79** [comment]
Sorry, it's not working at the moment

**Comment by Keokeo33** [comment]
Στις Τρί, 9 Νοε 2021, 13:19 ο χρήστης Orsai ***@***.***>
έγραψε:

**Comment by f-thomson** [comment]
Hello, Is there any plans to get it back on line? Would you have any documentation or sharable code that shows how to make the API calls for betting lines to all of the different bookies websites?

**Comment by Lisandro79** [comment]
For now we are not getting it back (we lack the resources to keep this project going indefinitely). Unfortunately, we cannot share that code (this is due to legal reasons). You could though go and scrap online websites and get the odds across bookies, there are plenty of resources online (e.g., oddshark, betexplorer, etc). 

Hope this helps

**Comment by Keokeo33** [comment]
Lisandro has excellent project but the secrets is in the odds

Στις Σάβ, 13 Νοε 2021, 03:49 ο χρήστης Orsai ***@***.***>
έγραψε:
