### ISSUE TITLE
Betfair exchange problem on dashboard

### ISSUE THREAD

**Issue by jcalderonzumba** [Lisandro79/BeatTheBookie#6]
You should probably remove Betfair from your dashboard and in the calculations. Betfair can move your "tips" in a bad way. Attaching an example that definitely affects the mean calculations and hence the tip becomes invalid.
<img width="472" alt="screen shot 2018-01-26 at 19 03 31" src="https://user-images.githubusercontent.com/2198097/35453813-d95e9b1a-02cb-11e8-8c08-f7a345c0cd5b.png">

As you can see there is 1.01 in Betfair and also, **Betfair is an exchange**, the odds are not set by a team of people calculating probabilities it's set by "the market".

**Comment by Lisandro79** [comment]
Hi Juan,
Yes, you are right, there is a problem in the calculation of the mean when Betfair provides very low odds. We will correct that soon. 

As Betfair was used for the strategy, we will keep its odds in the dashboard. Removing the bookie because it has some bug in reporting odds in some games can cause deviations from the results that we report in our paper. We would like to avoid this.

Please give us some days to fix this issue, we are involved in other tasks with higher priority at the moment.

Best

**Comment by Lisandro79** [comment]
Hi Juan,

The problem with Betfair has been fixed. Please let us know if any you see any other problems like this again. Thanks for the feedback

Cheers
